ALTER TABLE "Movie"
ADD COLUMN "regularPrice" DECIMAL(10,2) NOT NULL DEFAULT 250,
ADD COLUMN "vipPrice" DECIMAL(10,2) NOT NULL DEFAULT 350,
ADD COLUMN "couplePrice" DECIMAL(10,2) NOT NULL DEFAULT 600;
